import type { AuthResult, ToolMeta } from './auth.js'
import type { LogLevel, ToolContext } from './context.js'

/** Standardized validation error detail for a single field */
export interface ValidationDetail {
  /** Path to the invalid field (e.g. 'address.zip', 'items[0].name') */
  path: string
  /** Human-readable error message */
  message: string
}

/** Event captured during dispatch — progress reports and log entries */
export type DispatchEvent =
  | { type: 'progress'; progress: number; total?: number }
  | { type: 'log'; level: LogLevel; message: string; data?: Record<string, unknown> }

/** HTTP-oriented response metadata produced by a successful dispatch. */
export interface DispatchResponse {
  /** Override the default HTTP success status. */
  statusCode?: number
  /** Response headers to merge into the transport response. */
  headers?: Record<string, string>
  /** Optional content type for non-JSON or binary responses. */
  contentType?: string
}

/** Serialized failure details produced by a failed dispatch. */
export interface DispatchFailureInfo {
  message: string
  statusCode: number
  code?: string
  headers?: Record<string, string>
  details?: ValidationDetail[]
}

/** Successful result of pipeline.dispatch() — used by transports and lifecycle hooks. */
export interface DispatchSuccess {
  /** Request ID — always present, generated by the pipeline if not supplied */
  requestId: string
  ok: true
  value: unknown
  response?: DispatchResponse
  /** Progress/log events captured during dispatch (capped at 1000) */
  events?: DispatchEvent[]
  /** Number of events dropped due to cap overflow */
  eventsDropped?: number
}

/** Failed result of pipeline.dispatch() — used by transports and lifecycle hooks. */
export interface DispatchFailure {
  /** Request ID — always present, generated by the pipeline if not supplied */
  requestId: string
  ok: false
  error: DispatchFailureInfo
  /** Progress/log events captured during dispatch (capped at 1000) */
  events?: DispatchEvent[]
  /** Number of events dropped due to cap overflow */
  eventsDropped?: number
}

/** Discriminated dispatch result shared by HTTP, MCP, and stdio transports. */
export type DispatchOutcome = DispatchSuccess | DispatchFailure

/** Context passed to lifecycle hooks — always available, even when auth fails before ctx creation */
export interface DispatchLifecycleContext {
  requestId: string
  toolName: string
  transport: 'http' | 'mcp' | 'stdio'
  headers: Record<string, string>
  auth?: AuthResult
  tool?: ToolMeta
  /** Full tool context — present only if execution got past auth/validation */
  toolContext?: ToolContext
}

/** Called after a dispatch fails. `info.toolContext` can be absent if validation or auth failed first. */
export type OnDispatchErrorHook = (error: unknown, info: DispatchLifecycleContext) => void | Promise<void>
/** Called after a dispatch succeeds. */
export type OnDispatchSuccessHook = (result: DispatchSuccess, info: DispatchLifecycleContext) => void | Promise<void>
