import type { z } from 'zod'
import type {
  ToolAuth,
  PromptMessage,
  ConfigureServerHook,
  TransformToolDefinitionHook,
  TransformToolResultHook,
  ToolContext,
  AuthResult,
  AuthorizeHook,
  Logger,
  ToolCallMiddleware,
  ToolMeta,
  ResourceReadContext,
  PromptResolveContext,
} from '../types.js'
import type { DiscoveryOptions } from '../discovery.js'
import type { HttpMethod, HttpMethodInput } from '../http-method.js'
import type { Exposure } from '../registry.js'
import type { ObjectParamsSchema } from '../object-schema.js'
import type { BuildAppResult } from './build.js'
import type { BuilderSharedToolOptions, BuilderToolConfig } from '../tool-builder/config.js'

export type { DiscoveryEndpoint, DiscoveryOptions } from '../discovery.js'
export type { PromptResolveContext, ResourceReadContext } from '../types.js'

/**
 * Top-level configuration for a Graft application.
 */
export interface AppOptions<TAuth extends AuthResult = AuthResult> {
  name: string
  version?: string
  description?: string
  /** Public base URL used in generated discovery documents and OpenAPI output. */
  apiUrl?: string
  configureServer?: ConfigureServerHook
  transformToolDefinition?: TransformToolDefinitionHook
  /** MCP-only hook for reshaping tool results before they are serialized. */
  transformToolResult?: TransformToolResultHook
  /** Called before the standalone Node server starts listening. */
  onStart?: () => void | Promise<void>
  /** Called during standalone Node server shutdown. */
  onShutdown?: () => void | Promise<void>
  /** Authenticate incoming requests and return caller identity metadata. */
  authenticate?: (request: Request) => TAuth | Promise<TAuth>
  /** Override default role-based authorization for auth-protected tools/resources. */
  authorize?: AuthorizeHook<TAuth>
  /** Middleware wrapping every tool call. */
  onToolCall?: ToolCallMiddleware<TAuth>
  /** Optional CORS configuration for generated HTTP routes. */
  cors?: false | { origin?: string | string[] }
  /** Custom logger used by runtime code and tool contexts. */
  logger?: Logger
  /** Health-check endpoint configuration. */
  healthCheck?: boolean | { path?: string }
  /** Discovery endpoint configuration. */
  discovery?: DiscoveryOptions
}

/**
 * Configuration for registering a tool through `app.tool()`.
 */
export type ToolConfig<
  S extends ObjectParamsSchema = ObjectParamsSchema,
  TAuth extends AuthResult = AuthResult,
> = BuilderToolConfig<S, TAuth>

/**
 * Shared options applied to each tool in a `app.tools()` batch.
 */
export type SharedToolOptions = BuilderSharedToolOptions

/**
 * Configuration for registering a static resource via `app.resource()`.
 */
export interface ResourceConfig {
  uri: string
  name: string
  title?: string
  description: string
  mimeType?: string
  handler: (ctx: ResourceReadContext) => unknown | Promise<unknown>
  auth?: ToolAuth
  expose?: Exposure
  http?: { path?: string }
}

/**
 * Configuration for registering a URI-templated resource.
 */
export interface ResourceTemplateConfig<
  S extends ObjectParamsSchema = ObjectParamsSchema,
  TAuth extends AuthResult = AuthResult,
> {
  uriTemplate: string
  name: string
  description: string
  mimeType?: string
  params?: S
  auth?: ToolAuth
  handler: (params: z.output<S>, ctx: ToolContext<TAuth>) => unknown | Promise<unknown>
  expose?: Exposure
  http?: { path?: string }
}

/**
 * Configuration for registering a reusable prompt.
 */
export interface PromptConfig<S extends ObjectParamsSchema = ObjectParamsSchema> {
  name: string
  title?: string
  description: string
  params?: S
  handler: (params: z.output<S>, ctx: PromptResolveContext) => PromptMessage[] | Promise<PromptMessage[]>
  expose?: Exposure
  http?: { path?: string }
}

/**
 * Result returned by `App.build()`.
 */
export type BuildResult = BuildAppResult

/**
 * Descriptor for an HTTP route generated by `app.routes()`.
 */
export interface RouteDescriptor {
  method: HttpMethod
  path: string
  handler: (request: Request, pathParams?: Record<string, string>) => Promise<Response>
}

/**
 * Filter options for scoped middleware.
 */
export interface MiddlewareOptions {
  /** Restrict middleware to matching tools/resources. */
  filter?: (tool: ToolMeta) => boolean
}

/**
 * Options for registering an HTTP-only webhook tool.
 */
export interface WebhookConfig<TAuth extends AuthResult = AuthResult> {
  method?: HttpMethodInput
  path: string
  description: string
  auth?: ToolAuth
  handler: (params: Record<string, unknown>, ctx: ToolContext<TAuth>) => unknown | Promise<unknown>
}
